services:
  db:
    image: postgres:17
    container_name: giftup-db
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: nicolas
      POSTGRES_PASSWORD: SuaSenhaSegura
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nicolas -d crud"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./APICRUD
      dockerfile: Dockerfile
    container_name: giftup-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=crud;Username=nicolas;Password=SuaSenhaSegura
      Jwt__Key: Zk4sJf8wQ2uN9rX1vB7pE3aT6mC0yH5dR2oL8uK1nF4xS7tM9vP3qW6zY0bD2hJ
      Jwt__Issuer: MinhaAPI
      Jwt__Audience: MinhaAPIUsers
    ports:
      - "5000:5000"
    volumes:
      - ./APICRUD/Storage:/app/Storage

  frontend:
    build:
      context: ./giftup-frontend
      dockerfile: Dockerfile
    container_name: giftup-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
