// <auto-generated />
using System;
using APICRUD.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APICRUD.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20250907161307_RemoveTotalFromPedidos")]
    partial class RemoveTotalFromPedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APICRUD.Model.cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("datanascimento_cliente")
                        .HasColumnType("date");

                    b.Property<string>("email_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("islogged")
                        .HasColumnType("boolean");

                    b.Property<string>("nome_cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("APICRUD.Model.item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("foto_item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome_item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("preco_item")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("itens");
                });

            modelBuilder.Entity("APICRUD.Model.pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("integer");

                    b.Property<int>("status_pedido")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("cliente_id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("APICRUD.Model.pedidoItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("itemid")
                        .HasColumnType("integer");

                    b.Property<int>("pedidoid")
                        .HasColumnType("integer");

                    b.Property<int>("quantidade")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("itemid");

                    b.HasIndex("pedidoid");

                    b.ToTable("pedidoitens", (string)null);
                });

            modelBuilder.Entity("APICRUD.Model.pedido", b =>
                {
                    b.HasOne("APICRUD.Model.cliente", "clientes")
                        .WithMany()
                        .HasForeignKey("cliente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clientes");
                });

            modelBuilder.Entity("APICRUD.Model.pedidoItem", b =>
                {
                    b.HasOne("APICRUD.Model.item", "itens")
                        .WithMany()
                        .HasForeignKey("itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APICRUD.Model.pedido", "pedidos")
                        .WithMany("PedidoItens")
                        .HasForeignKey("pedidoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("itens");

                    b.Navigation("pedidos");
                });

            modelBuilder.Entity("APICRUD.Model.pedido", b =>
                {
                    b.Navigation("PedidoItens");
                });
#pragma warning restore 612, 618
        }
    }
}
