--
-- PostgreSQL database dump
--

\restrict XaStXQqRloXiuDJPhhCZCgKIu8iicHvTdwMimmVF7Df0ZVchXerG6LrarLGhSQd

-- Dumped from database version 16.10 (Debian 16.10-1.pgdg13+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: nicolas
--

CREATE TABLE public.clientes (
    id integer NOT NULL,
    nome_cliente text NOT NULL,
    datanascimento_cliente date NOT NULL,
    email_cliente text NOT NULL,
    senha text NOT NULL,
    islogged boolean NOT NULL
);


ALTER TABLE public.clientes OWNER TO nicolas;

--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: nicolas
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens; Type: TABLE; Schema: public; Owner: nicolas
--

CREATE TABLE public.itens (
    id integer NOT NULL,
    nome_item text NOT NULL,
    preco_item numeric NOT NULL,
    foto_item text NOT NULL
);


ALTER TABLE public.itens OWNER TO nicolas;

--
-- Name: itens_id_seq; Type: SEQUENCE; Schema: public; Owner: nicolas
--

ALTER TABLE public.itens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidoitens; Type: TABLE; Schema: public; Owner: nicolas
--

CREATE TABLE public.pedidoitens (
    id integer NOT NULL,
    pedidoid integer NOT NULL,
    itemid integer NOT NULL,
    quantidade integer NOT NULL
);


ALTER TABLE public.pedidoitens OWNER TO nicolas;

--
-- Name: pedidoitens_id_seq; Type: SEQUENCE; Schema: public; Owner: nicolas
--

ALTER TABLE public.pedidoitens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidoitens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: nicolas
--

CREATE TABLE public.pedidos (
    id integer NOT NULL,
    cliente_id integer NOT NULL,
    status_pedido integer NOT NULL
);


ALTER TABLE public.pedidos OWNER TO nicolas;

--
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: nicolas
--

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: nicolas
--

COPY public.clientes (id, nome_cliente, datanascimento_cliente, email_cliente, senha, islogged) FROM stdin;
1	Nicolas Pires	2008-02-29	nicolas@gmail.com	$2a$11$3x5k.W3fQ3DdRjYsRvOL6up3jFSI0TEaQjtZo/bDBBq.blznzkB7S	f
\.


--
-- Data for Name: itens; Type: TABLE DATA; Schema: public; Owner: nicolas
--

COPY public.itens (id, nome_item, preco_item, foto_item) FROM stdin;
1	Caneca personalizada	24.99	Storage/CanecaP.png
2	Copo termico	99.99	Storage/shopping.png
3	Relogio de mesa	149.99	Storage/download.png
\.


--
-- Data for Name: pedidoitens; Type: TABLE DATA; Schema: public; Owner: nicolas
--

COPY public.pedidoitens (id, pedidoid, itemid, quantidade) FROM stdin;
\.


--
-- Data for Name: pedidos; Type: TABLE DATA; Schema: public; Owner: nicolas
--

COPY public.pedidos (id, cliente_id, status_pedido) FROM stdin;
\.


--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nicolas
--

SELECT pg_catalog.setval('public.clientes_id_seq', 1, true);


--
-- Name: itens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nicolas
--

SELECT pg_catalog.setval('public.itens_id_seq', 3, true);


--
-- Name: pedidoitens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nicolas
--

SELECT pg_catalog.setval('public.pedidoitens_id_seq', 27, true);


--
-- Name: pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: nicolas
--

SELECT pg_catalog.setval('public.pedidos_id_seq', 9, true);


--
-- Name: clientes PK_clientes; Type: CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT "PK_clientes" PRIMARY KEY (id);


--
-- Name: itens PK_itens; Type: CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.itens
    ADD CONSTRAINT "PK_itens" PRIMARY KEY (id);


--
-- Name: pedidoitens PK_pedidoitens; Type: CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.pedidoitens
    ADD CONSTRAINT "PK_pedidoitens" PRIMARY KEY (id);


--
-- Name: pedidos PK_pedidos; Type: CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT "PK_pedidos" PRIMARY KEY (id);


--
-- Name: IX_pedidoitens_itemid; Type: INDEX; Schema: public; Owner: nicolas
--

CREATE INDEX "IX_pedidoitens_itemid" ON public.pedidoitens USING btree (itemid);


--
-- Name: IX_pedidoitens_pedidoid; Type: INDEX; Schema: public; Owner: nicolas
--

CREATE INDEX "IX_pedidoitens_pedidoid" ON public.pedidoitens USING btree (pedidoid);


--
-- Name: IX_pedidos_cliente_id; Type: INDEX; Schema: public; Owner: nicolas
--

CREATE INDEX "IX_pedidos_cliente_id" ON public.pedidos USING btree (cliente_id);


--
-- Name: pedidoitens FK_pedidoitens_itens_itemid; Type: FK CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.pedidoitens
    ADD CONSTRAINT "FK_pedidoitens_itens_itemid" FOREIGN KEY (itemid) REFERENCES public.itens(id) ON DELETE CASCADE;


--
-- Name: pedidoitens FK_pedidoitens_pedidos_pedidoid; Type: FK CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.pedidoitens
    ADD CONSTRAINT "FK_pedidoitens_pedidos_pedidoid" FOREIGN KEY (pedidoid) REFERENCES public.pedidos(id) ON DELETE CASCADE;


--
-- Name: pedidos FK_pedidos_clientes_cliente_id; Type: FK CONSTRAINT; Schema: public; Owner: nicolas
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT "FK_pedidos_clientes_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict XaStXQqRloXiuDJPhhCZCgKIu8iicHvTdwMimmVF7Df0ZVchXerG6LrarLGhSQd

